defaultCategoryId: 1

logging:
  level: INFO
  loggers:
    patternexperiment: DEBUG
    
database:
  driverClass: org.postgresql.Driver
  user: pg-user
  password: iAMs00perSecrEET
  url: jdbc:postgresql://db.example.com/db-prod
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  maxWaitForConnection: 1s
  validationQuery: SELECT 1
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: false