server:
  applicationConnectors:
  - type: http
    port: 8030
  adminConnectors:
  - type: http
    port: 8031

jerseyClient:
  timeout: 5s
  connectionTimeout: 5s

logging:
  level: INFO
  loggers:
    patternexperiment: DEBUG