server:
  applicationConnectors:
  - type: http
    port: 8020
  adminConnectors:
  - type: http
    port: 8021

jerseyClient:
  timeout: 5s
  connectionTimeout: 5s

logging:
  level: INFO
  loggers:
    patternexperiment: DEBUG
