server:
  applicationConnectors:
  - type: http
    port: 8040
  adminConnectors:
  - type: http
    port: 8041

jerseyClient:
  timeout: 5s
  connectionTimeout: 5s

logging:
  level: INFO
  loggers:
    patternexperiment: DEBUG
